# Generated by Django 6.1.1 on 2026-09-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='category',
        ),
        migrations.RemoveField(
            model_name='character',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='character',
            name='description',
        ),
        migrations.RemoveField(
            model_name='character',
            name='gold_reward',
        ),
        migrations.RemoveField(
            model_name='character',
            name='title',
        ),
        migrations.RemoveField(
            model_name='character',
            name='xp_reward',
        ),
        migrations.AddField(
            model_name='quest',
            name='category',
            field=models.CharField(default='Coding', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='gold_reward',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='quest',
            name='xp_reward',
            field=models.IntegerField(default=10),
        ),
    ]
