# Generated by Django 6.1.1 on 2026-09-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_character_category_remove_character_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
